### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by proffapt** [metakgp/kronos#4]
Refactor the documentation style to https://github.com/metakgp/README.md

**Comment by Bikram-ghuku** [comment]
Can I work on this issue?

**Comment by proffapt** [comment]
No, get someone else. You have other things to do :)

**Comment by Bikram-ghuku** [comment]
MB, sure others can work on this one :)

**Comment by Ananya-m0140** [comment]
I would like to work on this issue.

**Comment by proffapt** [comment]
@Ananya-m0140 any progress? This is not some tedious task.

**Comment by Ananya-m0140** [comment]
Almost done, I'll create the pull request by tomorrow.

**Comment by proffapt** [comment]
You should create the PR right away and leave it as a [draft](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

**Comment by proffapt** [comment]
Done in #5
