### ISSUE TITLE
Clicking wiki button for courses having no wiki opens a blank page

### ISSUE THREAD

**Issue by parth-paradkar** [metakgp/Kronos#74]
I think the button should not be displayed for courses not having wikis. While this [line](https://github.com/metakgp/Kronos/blob/b46dd4efcb7696afb66f349714496c7a0b986d5a/templates/kronos.html#L208) seems to be handling it, there is no tag with id `Courselink`. We can either conditionally display the button, or add the missing id `Courselink` in the `button` tag.

**Comment by Ayushk4** [comment]
Thanks.
This should be a good first issue.

**Comment by marcozzxx810** [comment]
Can I help with this task?
